### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by AmineHLub** [mmsesay/final-capstone-backend#21]
**We are only 4 that will be working on this project.**

Team member **number 1**: _@sheylaPozo_ 
Team member **number 2**: _@mmsesay_ 
Team member **number 3**: _@CollinsTatang_ 
Team member **number 4**: _@AmineHLub_ 

Kanban Link : https://github.com/mmsesay/final-capstone-backend/projects/1

Kanban Screenshot:
![Screenshot from 2022-02-18 15-59-55](https://user-images.githubusercontent.com/39523312/154718667-3669cec8-df4d-4554-af0a-f010b224a07e.png)

**Comment by mmsesay** [comment]
Thank you @MuriloRoque.
